force-app/main/default/objects/GB_weather__c/GB_weather__c.object-meta.xml
<CustomObject>
    <description>Used to store weather information for the customer&apos;s local area</description>
    <label>Weather</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GB_weather__c/fields/GB_Contact__c.field-meta.xml
<CustomField>
    <fullName>GB_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Weather</relationshipLabel>
    <relationshipName>Weather</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GB_weather__c/fields/GB_contactId__c.field-meta.xml
<CustomField>
    <fullName>GB_contactId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Contact ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/GB_weather__c/fields/GB_Description__c.field-meta.xml
<CustomField>
    <fullName>GB_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GB_weather__c/fields/GB_iconUrl__c.field-meta.xml
<CustomField>
    <fullName>GB_iconUrl__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Icon URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GB_weather__c/fields/GB_Temperature__c.field-meta.xml
<CustomField>
    <fullName>GB_Temperature__c</fullName>
    <label>Temperature</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GB_weatherCalloutService.cls
public with sharing class GB_weatherCalloutService {
    
    @AuraEnabled
    public static GB_weather__c makeCallout(String parameter, String contactId, Boolean isFromLwc) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        HttpResponse response = new HttpResponse();
        String apiKey = String.valueOf(GB_customSettingsAccessor.getFieldValue('GB_apiKey__c'));
        String endpoint = 'callout:GB_WeatherAPI/v1/current.json?key=' + apiKey + '&q=' + parameter;
        request.setEndpoint(endpoint);
        request.setMethod('GET');
        GB_weather__c weatherObject = new GB_weather__c();
        try {
            response = http.send(request);
            if (response.getStatusCode() == 200) {
                Map<String,Object> responseMap = (Map<String,Object>)JSON.deserializeUntyped(response.getBody());
                //Enhancement: check to see if user wants celcius or fahrenheit
                Map<String,Object> currentWeather = (Map<String,Object>)responseMap.get('current');
                weatherObject.GB_Temperature__c = Decimal.valueOf(String.valueOf(currentWeather.get('temp_c')));
                Map<String,Object> condition = (Map<String,Object>)currentWeather.get('condition');
                weatherObject.GB_iconUrl__c = String.valueOf(condition.get('icon'));
                weatherObject.GB_Description__c = String.valueOf(condition.get('text'));
                weatherObject.GB_Contact__c = contactId;
                weatherObject.GB_contactId__c = contactId;
            }
            else {
                return null;
            }
        }
        catch (CalloutException e) {
            //Handle errors - error logging?
            return null;
        }
        if (isFromLwc) {
            upsert weatherObject GB_contactId__c;
        }
        return weatherObject;

    }
}