force-app/main/default/objects/GB_weather__c/GB_weather__c.object-meta.xml
<CustomObject>
    <description>Used to store weather information for the customer&apos;s local area</description>
    <label>Weather</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GB_weather__c/fields/GB_contactId__c.field-meta.xml
<CustomField>
    <fullName>GB_contactId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Contact ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/GB_weatherAccessorTest.cls
@IsTest
public with sharing class GB_weatherAccessorTest {
    
    @IsTest
    public static void testGetWeatherLocal() {
        GB_weather__c weatherRecord = new GB_weather__c();
        Test.setMock(HttpCalloutMock.class, new GB_weatherDataMock());
        Contact con = new Contact(LastName='Test', MailingCity='Test');
        Test.startTest();
        insert con;
        Test.stopTest();
        weatherRecord = GB_weatherAccessor.getWeatherForContact(con.Id, false);
        System.assertEquals(weatherRecord.GB_contactId__c, con.Id);
    }

    @IsTest
    public static void testGetWeatherCallout() {
        GB_weather__c weatherRecord = new GB_weather__c();
        Test.setMock(HttpCalloutMock.class, new GB_weatherDataMock());
        Contact con = new Contact(LastName='Test', MailingCity='Test');
        Test.startTest();
        insert con;
        weatherRecord = GB_weatherAccessor.getWeatherForContact(con.Id, true);
        Test.stopTest();
        weatherRecord = GB_weatherAccessor.getWeatherForContact(con.Id, false);
        System.assertEquals(weatherRecord.GB_contactId__c, con.Id);
    }
}